### ISSUE TITLE
Can we add flake-utils?

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [NixOS/flake-registry#9]
What are the rules for all this? Which flakes can be added here anyways?

I'd love to see flake-utils added here because basically everyone uses it https://github.com/search?q=flake-utils+extension%3Anix&type=code 

@numtide thoughts?

**Comment by gytis-ivaskevicius** [comment]
Also, is there a reason why there is no README? If there is a need I could quickly sketch something up and PR it over (Something with an answer of what can be included in this repo would be great)

**Comment by gytis-ivaskevicius** [comment]
nvm, dumb idea, prob creates more problems than it solves. 
Some readme would be nice tho

**Comment by rocky-fuchsian-frog** [comment]
@gytis-ivaskevicius I'd like to know why you closed this.

**Comment by gytis-ivaskevicius** [comment]
There is a PR to merge flake-utils into nixpkgs and even tho this would save one line in your flake.nix - it does not add any additional value like apps/packages which you could use via CLI
